### PR TITLE
Update documentation for displaying available services

### PR DESCRIPTION
**Pull request by pivotal-grapevine**

### CODE REVIEW

**Comment by flavorjones** [comment]
+1

**Comment by flavorjones** [comment]
This pull request demonstrates the danger in making an in-browser GitHub edit while using @panicsteve's ["cloud-to-butt" chrome extension](https://github.com/panicsteve/cloud-to-butt).

**Comment by maebert** [comment]
Meanwhile, at @panicinc: :trollface:

**Comment by divarvel** [comment]
This pull request demonstrates the need to read diffs before submitting a pull request.

**Pull request closed without merging**
