### PR TITLE
rootfs_lucid64 pkg for warden [fixes #3]

### LINKED ISSUE #3: Fix warden rootfs
I have not yet tested this release but saw the rootfs path does not references the rootfs package.

Related PR https://github.com/cloudfoundry/cf-release/pull/83

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
@rkoster does this patch allow you to run postgresql or mysql service?

**Comment by rkoster** [comment]
I had to apply this fix when I had service node and gateway running but when I executed `cf create-service` it would fail. The problem was found on the service node which complained about a file not found. This was because the file it was looking for in the warden container was not in the filesystem. 

I'm currently rebuilding our infrastructure on folsom (we where running on essex) so have no way of testing.

**Comment by rkoster** [comment]
Here is the original pull request with more info https://github.com/cloudfoundry/cf-release/pull/83.

**Comment by drnic** [comment]
I think I've applied this fix exactly as you had it.

**Comment by RobDay-Reynolds** [comment]
The postgresql job was removed, so this only affected mysql node job.

@mariash & @monkeyherder

**Pull request merged**
